SELECT * FROM BEERS;

SELECT * FROM BARS;

SELECT * FROM DOLGOZO;

SELECT * FROM FIZ_KATEGORIA;

SELECT avg(FIZETES),COUNT(*) FROM DOLGOZO GROUP BY OAZON;

SELECT avg(FIZETES),COUNT(*) FROM DOLGOZO GROUP BY OAZON HAVING COUNT(*)>2;

SELECT avg(FIZETES),COUNT(*) FROM DOLGOZO WHERE FIZETES > 1000 GROUP BY OAZON HAVING COUNT(*)>2;

SELECT avg(FIZETES),TELEPHELY,COUNT(*) FROM DOLGOZO NATURAL JOIN OSZTALY GROUP BY OAZON, TELEPHELY HAVING COUNT(*)>=4;


-- ez igazából a feladat, csak gyökerek szegények
SELECT OSZTALY.ONEV,OSZTALY.TELEPHELY FROM DOLGOZO, OSZTALY WHERE DOLGOZO.OAZON = DOLGOZO.OAZON GROUP BY OSZTALY.ONEV, OSZTALY.TELEPHELY HAVING AVG(DOLGOZO.FIZETES) > 2000;


SELECT kategoria from ( SELECT * FROM FIZ_KATEGORIA,DOLGOZO WHERE DOLGOZO.FIZETES BETWEEN FIZ_KATEGORIA.ALSO AND FIZ_KATEGORIA.FELSO) GROUP BY KATEGORIA  HAVING COUNT(*)=3;


SELECT * FROM DRINKERS;



