DROP TABLE dolg2;
CREATE TABLE dolg2 AS SELECT * FROM nikovits.dolgozo;

CREATE TABLE oszt2 AS SELECT * FROM nikovits.osztaly;



--DELETE FROM DOLG2 WHERE JUTALEK IS NULL;

--DELETE FROM DOLG2 WHERE EXTRACT(YEAR FROM BELEPES)<1982;

--DELETE FROM DOLG2 WHERE DKOD IN (SELECT DKOD FROM DOLG2 NATURAL JOIN OSZTALY WHERE TELEPHELY ='DALLAS');

SELECT * FROM DOLG2;

SELECT AVG(FIZETES) FROM DOLG2;

DELETE FROM DOLG2 WHERE FIZETES <  (SELECT AVG(FIZETES) FROM DOLG2);

DELETE FROM DOLG2 WHERE FIZETES =  (SELECT MAX(FIZETES) FROM DOLG2);

DELETE FROM OSZT2 WHERE OAZON = (SELECT COUNT(DKOD) FROM DOLG2 NATURAL JOIN OSZT2 INNER JOIN FIZ_KATEGORIA ON DOLG2.FIZETES BETWEEN FIZ_KATEGORIA.ALSO AND FIZ_KATEGORIA.FELSO WHERE FIZ_KATEGORIA.KATEGORIA = 2 GROUP BY OAZON HAVING COUNT(*)=2); 

INSERT INTO DOLG2 (DKOD, DNEV, OAZON, BELEPES, FIZETES) VALUES (1, 'KOVACS', 10, SYSDATE, (SELECT AVG(FIZETES) FROM DOLG2));

Select * FROM osztaly;

SELECT * FROM DOLG2;

UPDATE DOLG2 SET FIZETES = FIZETES * 1.20 WHERE OAZON = 20;

UPDATE DOLG2 SET FIZETES = FIZETES+500 WHERE JUTALEK = NULL OR FIZETES < (SELECT AVG(FIZETES) FROM DOLG2);

UPDATE DOLG2 SET JUTALEK = NVL(JUTALEK,0) + (SELECT MAX(JUTALEK) FROM DOLG2);

UPDATE DOLG2 SET DNEV = 'LOSER' WHERE FIZETES = (SELECT MIN(FIZETES) FROM DOLG2);

UPDATE DOLG2 SET JUTALEK = NVL(JUTALEK,0) + 3000 WHERE DKOD IN (SELECT D1.FONOKE FROM DOLG2 d1 INNER JOIN DOLG2 d2 ON D1.FONOKE = D2.DKOD GROUP BY D1.FONOKE HAVING COUNT(*) > 1 );

UPDATE DOLG2 SET JUTALEK = NVL(JUTALEK,0) + (SELECT MIN(FIZETES) FROM DOLG2) WHERE DKOD IN (SELECT D1.FONOKE FROM DOLG2 d1 INNER JOIN DOLG2 d2 ON D1.FONOKE = D2.DKOD GROUP BY D1.FONOKE HAVING COUNT(*) > 0 );

